export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAIL = "VERIFICATION_FAIL";

export const SENDEMAIL_REQUEST = "SENDEMAIL_REQUEST";
export const SENDEMAIL_SUCCESS = "SENDEMAIL_SUCCESS";
export const SENDEMAIL_FAIL = "SENDEMAIL_FAIL";

export const VERIFICATIONSTATUS_REQUEST = "VERIFICATIONSTATUS_REQUEST";
export const VERIFICATIONSTATUS_SUCCESS = "VERIFICATIONSTATUS_SUCCESS";
export const VERIFICATIONSTATUS_FAIL = "VERIFICATIONSTATUS_FAIL";

export const IS_USER_LOGGED_IN_REQUEST = "IS_USER_LOGGED_IN_REQUEST";
