export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST'
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS'
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL'
export const CREATE_INVOICE_RESET = 'CREATE_INVOICE_RESET'

export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST'
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS'
export const GET_INVOICES_FAIL = 'GET_INVOICES_FAIL'
export const GET_INVOICES_RESET = 'GET_INVOICES_RESET'

export const GET_INVOICE_BY_ID_REQUEST = 'GET_INVOICE_BY_ID_REQUEST'
export const GET_INVOICE_BY_ID_SUCCESS = 'GET_INVOICE_BY_ID_SUCCESS'
export const GET_INVOICE_BY_ID_FAIL = 'GET_INVOICE_BY_ID_FAIL'
export const GET_INVOICE_BY_ID_RESET = 'GET_INVOICE_BY_ID_RESET'

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST'
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS'
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL'
export const DELETE_INVOICE_RESET = 'DELETE_INVOICE_RESET'

export const UPDATE_INVOICE_REQUEST = 'UPDATE_INVOICE_REQUEST'
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS'
export const UPDATE_INVOICE_FAIL = 'UPDATE_INVOICE_FAIL'
export const UPDATE_INVOICE_RESET = 'UPDATE_INVOICE_RESET'

export const GET_INVOICE_BY_USER_ID_REQUEST = 'GET_INVOICE_BY_USER_ID_REQUEST'
export const GET_INVOICE_BY_USER_ID_SUCCESS = 'GET_INVOICE_BY_USER_ID_SUCCESS'
export const GET_INVOICE_BY_USER_ID_FAIL = 'GET_INVOICE_BY_USER_ID_FAIL'
export const GET_INVOICE_BY_USER_ID_RESET = 'GET_INVOICE_BY_USER_ID_RESET'